SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO


alter        PROCEDURE [ABSSP_ADMIN_DIESEL_RPT]
	(@RPT_ST_DATE	DATETIME = '201310'
	,@RPT_END_DATE	DATETIME = '201310'
	,@RPT_ST_BRANCH	CHAR(15) = '1501'
	,@RPT_END_BRANCH CHAR(15) = '1501'
	,@RPT_ST_TYPE	CHAR(1) = 'A'
	,@RPT_END_TYPE CHAR(1) = 'Z')

AS

  SELECT 
    WK.ADM_DIESEL_TRANS_TYPE AS RPT_DIESEL_TYPE
    ,WK.ADM_DIESEL_TRANS_NO AS RPT_DIESEL_TRANS_NO
    ,WK.ADM_DIESEL_TRANS_DATE AS RPT_DATE
    ,WK.ADM_DIESEL_BRANCH_CODE AS RPT_BRANCH_CODE
    ,WK.ADM_DIESEL_DEPT_CODE AS RPT_DEPT_CODE
     ,WK.ADM_DIESEL_TRANS_UNIT_PRICE AS RPT_DIESEL_PRICE
     ,WK.ADM_DIESEL_SUPPLY_COY AS RPT_SUPPLY_COY


,ADM_DIESEL_TRANS_TYPE =
	CASE  WK.ADM_DIESEL_TRANS_TYPE
		WHEN 'I' THEN 'ISSUE'
                ELSE 'RECEIPT'
	END
   ,ADM_DIESEL_AMOUNT  = 
     CASE  WK.ADM_DIESEL_TRANS_TYPE
		WHEN 'I' THEN  
                ADM_DIESEL_TRANS_AMT  * -1  
ELSE
                 ADM_DIESEL_TRANS_AMT
END 
   ,ADM_DIESEL_QUANTITY  = 
     CASE  WK.ADM_DIESEL_TRANS_TYPE
		WHEN 'I' THEN  
                ADM_DIESEL_TRANS_QTY  * -1  
ELSE
                 ADM_DIESEL_TRANS_QTY
END 


    ,(SELECT CTBRA_NAME FROM [ABSBRNCHTAB] WHERE CTBRA_NUM = WK.ADM_DIESEL_BRANCH_CODE)AS RPT_BRANCH_NAME
    ,(SELECT CTINSRD_LONG_DESCR FROM ABSDEPTTAB WHERE CTINSRD_NO = wk.ADM_DIESEL_DEPT_CODE) AS RPT_DEPT_NAME
    , INS.ADM_TAB_ITEM_DESC AS RPT_SUPPLY_COY_NAME

   ,ADM_DIESEL_USE_SUPPLY_DESC  = 
     CASE  WK.ADM_DIESEL_TRANS_TYPE
		WHEN 'I' THEN  
                (SELECT CTINSRD_LONG_DESCR FROM ABSDEPTTAB WHERE CTINSRD_NO = wk.ADM_DIESEL_DEPT_CODE)
		ELSE
                INS.ADM_TAB_ITEM_DESC
		END
    FROM ADM_DIESEL_BILLS  AS WK
    LEFT JOIN [ADM_MAINT_CODE_TABLE]  AS INS
       ON (INS.ADM_TAB_ITEM_CODE_NO = WK.ADM_DIESEL_SUPPLY_COY AND INS.ADM_TAB_CLASS_CODE = '002')

 WHERE WK.ADM_DIESEL_TRANS_DATE >= @RPT_ST_DATE AND WK.ADM_DIESEL_TRANS_DATE <= @RPT_END_DATE AND
 WK.ADM_DIESEL_BRANCH_CODE >= @RPT_ST_BRANCH AND WK.ADM_DIESEL_BRANCH_CODE <= @RPT_END_BRANCH AND
 WK.ADM_DIESEL_TRANS_TYPE >= @RPT_ST_TYPE AND WK.ADM_DIESEL_TRANS_TYPE <= @RPT_END_TYPE

 ORDER BY WK.ADM_DIESEL_BRANCH_CODE, WK.ADM_DIESEL_TRANS_DATE
 
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

