SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE        PROCEDURE [ABSSP_ADMIN_INS_PREM_RPT]
	(@RPT_ST_DATE	DATETIME = '201310'
	,@RPT_END_DATE	DATETIME = '201310'
	,@RPT_ST_BRANCH	CHAR(15) = '1501'
	,@RPT_END_BRANCH CHAR(15) = '1501')

AS

  SELECT 
    WK.ADM_INS_PREM_COVER_TYPE AS RPT_INS_PREM_TYPE
    ,WK.ADM_INS_PREM_TRANS_NO AS RPT_INS_PREM_TRANS_NO
    ,WK.ADM_INS_PREM_TRANS_DATE AS RPT_DATE
    ,WK.ADM_INS_PREM_BRANCH_CODE AS RPT_BRANCH_CODE
    ,WK.ADM_INS_PREM_DEPT_CODE AS RPT_DEPT_CODE
     ,WK.ADM_INS_PREM_POLICY_NO AS RPT_POLICY_NO
     ,WK.ADM_INS_PREM_BROKER_CODE AS RPT_BROKER_CD
     ,WK.ADM_INS_PREM_INSURER_CODE AS RPT_INSURER_CD
     ,WK.ADM_INS_PREM_START_DATE AS RPT_PREM_ST_DATE
     ,WK.ADM_INS_PREM_END_DATE AS RPT_PREM_END_DATE
    ,WK.ADM_INS_PREM_DESC AS RPT_DESC
    ,WK.ADM_INS_PREM_SUM_INSURED AS RPT_SA_AMT
    ,WK.ADM_INS_PREM_PREMIUM_AMT AS RPT_PREM_AMT
    ,(SELECT CTBRA_NAME FROM [ABSBRNCHTAB] WHERE CTBRA_NUM = WK.ADM_INS_PREM_BRANCH_CODE)AS RPT_BRANCH_NAME
    ,(SELECT CTINSRD_LONG_DESCR FROM ABSDEPTTAB WHERE CTINSRD_NO = WK.ADM_INS_PREM_DEPT_CODE) AS RPT_DEPT_NAME
    , BRK.ADM_TAB_ITEM_DESC AS RPT_BROKER_NAME
    , INS.ADM_TAB_ITEM_DESC AS RPT_INSURER_NAME

    FROM ADM_INSURANCE_PREM_BILLS  AS WK
    LEFT JOIN [ADM_MAINT_CODE_TABLE]  AS BRK
       ON (BRK.ADM_TAB_ITEM_CODE_NO = WK.ADM_INS_PREM_BROKER_CODE AND BRK.ADM_TAB_CLASS_CODE = '005')
    LEFT JOIN [ADM_MAINT_CODE_TABLE]  AS INS
       ON (INS.ADM_TAB_ITEM_CODE_NO = WK.ADM_INS_PREM_INSURER_CODE AND INS.ADM_TAB_CLASS_CODE = '004')

 WHERE WK.ADM_INS_PREM_TRANS_DATE >= @RPT_ST_DATE AND WK.ADM_INS_PREM_TRANS_DATE <= @RPT_END_DATE AND
 WK.ADM_INS_PREM_BRANCH_CODE >= @RPT_ST_BRANCH AND WK.ADM_INS_PREM_BRANCH_CODE <= @RPT_END_BRANCH

    ORDER BY WK.ADM_INS_PREM_BRANCH_CODE, WK.ADM_INS_PREM_TRANS_DATE

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

